/*
tạo 1 bản temp để lưu được thứ tự của OCCUPATION và sắp xếp NAME, Từ đó print ra Name theo group row_number
*/

SELECT 
MIN(CASE WHEN OCCUPATION = 'DOCTOR'    THEN NAME ELSE NULL END) ,
MIN(CASE WHEN OCCUPATION = 'PROFESSOR' THEN NAME ELSE NULL END) ,
MIN(CASE WHEN OCCUPATION = 'SINGER'    THEN NAME ELSE NULL END) ,
MIN(CASE WHEN OCCUPATION = 'ACTOR'     THEN NAME ELSE NULL END)
FROM
(SELECT OCCUPATION, NAME, ROW_NUMBER() OVER (PARTITION BY OCCUPATION ORDER BY NAME) AS OCCUS
FROM OCCUPATIONS) AS Temp
GROUP BY OCCUS